import React, { useState } from 'react';
import { Copy, Check, Wand2, Share2 } from 'lucide-react';

interface AnalysisResultProps {
  prompt: string;
}

const AnalysisResult: React.FC<AnalysisResultProps> = ({ prompt }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(prompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleShare = () => {
    const text = `Fashion Prompt generated by PopStyle Prompter! 🎨✨\n\n${prompt}\n\n#PopStylePrompter #AIArt`;
    const url = "https://twitter.com/intent/tweet?text=" + encodeURIComponent(text);
    window.open(url, '_blank');
  };

  // Split tags for better visual presentation
  const tags = prompt.split(',').map(tag => tag.trim()).filter(tag => tag.length > 0);

  return (
    <div className="w-full max-w-3xl mx-auto mt-8 animate-in fade-in slide-in-from-bottom-8 duration-500">
      <div className="bg-white border-4 border-pop-black rounded-3xl p-6 md:p-8 shadow-hard relative overflow-hidden">
        
        {/* Header Label */}
        <div className="absolute top-0 left-0 bg-pop-purple text-white font-pop px-6 py-2 rounded-br-2xl border-r-4 border-b-4 border-pop-black z-10">
          <span className="flex items-center gap-2">
            <Wand2 size={18} /> Result
          </span>
        </div>

        <div className="mt-8 mb-6">
           <h3 className="text-xl font-pop mb-4 text-center text-pop-black">生成されたプロンプト</h3>
           
           {/* Visual Tag Cloud */}
           <div className="flex flex-wrap gap-2 justify-center mb-6">
             {tags.map((tag, index) => (
               <span 
                key={index} 
                className={`
                  px-3 py-1 rounded-full border-2 border-pop-black text-sm font-bold font-outfit
                  ${index % 3 === 0 ? 'bg-pop-pink/20 text-pink-700' : 
                    index % 3 === 1 ? 'bg-pop-cyan/20 text-teal-700' : 
                    'bg-pop-yellow/20 text-amber-700'}
                `}
               >
                 #{tag}
               </span>
             ))}
           </div>

           {/* Raw Text Area */}
           <div className="bg-gray-50 p-4 rounded-xl border-2 border-pop-black font-outfit text-lg leading-relaxed text-pop-black max-h-60 overflow-y-auto">
             {prompt}
           </div>
        </div>

        <div className="flex flex-col md:flex-row justify-center gap-4">
          <button
            onClick={handleCopy}
            className={`
              flex items-center justify-center gap-3 px-8 py-3 rounded-full font-pop text-lg border-4 border-pop-black shadow-hard transition-all active:translate-x-[2px] active:translate-y-[2px] active:shadow-none w-full md:w-auto
              ${copied ? 'bg-green-400 text-white' : 'bg-pop-yellow text-pop-black hover:-translate-y-1 hover:shadow-hard-lg'}
            `}
          >
            {copied ? (
              <>
                <Check strokeWidth={3} /> コピーOK!
              </>
            ) : (
              <>
                <Copy strokeWidth={3} /> コピーする
              </>
            )}
          </button>

          <button
            onClick={handleShare}
            className="flex items-center justify-center gap-3 px-8 py-3 rounded-full font-pop text-lg border-4 border-pop-black shadow-hard transition-all bg-black text-white hover:-translate-y-1 hover:shadow-hard-lg active:translate-x-[2px] active:translate-y-[2px] active:shadow-none w-full md:w-auto"
          >
            <Share2 strokeWidth={3} size={20} />
            Xでシェア
          </button>
        </div>

        {/* Decorative Elements */}
        <div className="absolute -right-6 -bottom-6 w-24 h-24 bg-pop-cyan rounded-full border-4 border-pop-black z-0 opacity-20"></div>
        <div className="absolute -left-4 bottom-12 w-12 h-12 bg-pop-pink rounded-full border-4 border-pop-black z-0 opacity-20"></div>
      </div>
    </div>
  );
};

export default AnalysisResult;